#!/usr/bin/python

import sys, getopt
import time;  # This is required to include time module.

inputfile =""
outputfile =""
param =""

def openFile(argv):
   try:
      opts, args = getopt.getopt(argv,"hi:o:p:",["ifile=","ofile=","para="])
   except getopt.GetoptError:
      print 'html2Ccode.py -i <inputfile> -o <outputfile> -p <parameter>'
      print str(IOError)
      sys.exit(2)
   for opt, arg in opts:
      if opt == '-h':
         print 'html2Ccode.py -i <inputfile> -o <outputfile> -p <parameter>'
         sys.exit(3)
      elif opt in ("-i", "--ifile"):
         inputfile = arg
      elif opt in ("-o", "--ofile"):
         outputfile = arg
      elif opt in ("-p", "--para"):
         parameter = arg
   print 'Input file is ', inputfile
   print 'Output file is ', outputfile
   print 'Parameter is ', parameter
   return inputfile,outputfile,parameter

def main(argv):
   Ifile, Ofile, Param = openFile(argv)
   try:
      localtime = time.asctime( time.localtime(time.time()) )
      InputObj = open(Ifile,'r+')
      OutputObj = open(Ofile,'w+')
      OutputObj.write('/*Generated by html2Ccode.py\n')
      OutputObj.write('Made by PlayElek.com\n')
      OutputObj.write('Generated on \n')
      OutputObj.write(localtime + '\n')
      OutputObj.write('Parameter is '+ Param +'\n')
      OutputObj.write('*/\n')
      #OutputObj.write(InputObj.readline())
      endline = 0
      txtsize = 0
      try:
         OutputObj.write("#ifndef " + Param +"_H\n")
         OutputObj.write("#define " + Param +"_H\n")
         OutputObj.write("int "+Param+"Size = 0;\n")
         #OutputObj.write("char "+Param+"[2000];\n")
         #OutputObj.write(Param+"Size = snprintf("+Param+",")
         #OutputObj.write("char " + Param +"[] = {\n"+'"')
         OutputObj.write("char "+Param+'[] = "HTTP/1.1 200 OK\\r\\nContent-Type: text/html\\r\\n\\r\\n\\'+'\n')
         #OutputObj.write('"') 
         for c in InputObj.read():
            if c == "'" or c == '"': 
               OutputObj.write("\\"+c)
               endline = 0
            elif c=='\n' or c=="\n":
               if endline == 0:
                  OutputObj.write("\\n\\"+"\n")
                  endline = 1
            else:
               OutputObj.write(c)
               endline = 0
         #OutputObj.write('");\n')
         OutputObj.write("\";\n")
         #OutputObj.write("int "+Param+"Size = "+str(txtsize+1)+';\n')
         OutputObj.write("#endif\n")
      except Exception as e:
         print str(e)
         sys.exit(4)

   except IOError:
      print str(IOError)
      print "Cannot open file"



if __name__ == "__main__":
   main(sys.argv[1:])