/*Generated by html2Ccode.py
Made by PlayElek.com
Generated on 
Thu Apr 06 17:27:10 2017
Parameter is htmlCode
*/
#ifndef htmlCode_H
#define htmlCode_H
#include <string.h>
#define pageCount 27
String htmlCode[pageCount];
void htmlCode_init(void){
htmlCode[0] = "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n\
<!DOCTYPE html>\n\
<html>\n\
<head>\n\
<title>Nodemcu Control</title>\n\
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">\n\
</head>\n\
<body>\n\
<h4>Nodemcu Controller</h4>\n\
<p>created by playelek.com</p>\n\
<p id=\"div1\"></p>\n\
<div id=\"displayId\"></div>\n\
";
htmlCode[1] = "\
<h4>LED ON/OFF</h4>\n\
<input type=\"checkbox\" class=\"cmn-toggle cmn-toggle-round\" id=\"led1\" onchange=\"sendVal()\">\n\
<label for=\"led1\"></label>\n\
<p id=\"chkboxVal\"></p>\n\
";
htmlCode[2] = "\
<h4>SERVOS</h4>\n\
<input type=\"range\" id=\"servo1\" min=\"0\" max=\"180\" value=\"90\" oninput=\"sendVal();rangeVal1.value=value;\">\n\
<output id=\"rangeVal1\">90</output>\n\
<input type=\"range\" id=\"servo2\" min=\"0\" max=\"180\" value=\"90\" oninput=\"sendVal();rangeVal2.value=value;\">\n\
<output id=\"rangeVal2\">90</output>\n\
";
htmlCode[3] = "\
<script>\n\
var ajax = null;\n\
if (window.XMLHttpRequest) {\n\
    // code for modern browsers\n\
    ajax = new XMLHttpRequest();\n\
} else if (window.ActiveXObject) {\n\
    // code for IE6, IE5\n\
    ajax = new ActiveXObject(\"Microsoft.XMLHTTP\");\n\
} else { \n\
    // code for stone age web browser\n\
    document.getElementById(\'div1\').innerHTML = \'Ajax is not supported by this browser\';\n\
}\n\
";
htmlCode[4] = "\
function sendVal() \n\
{\n\
    var x = document.getElementById(\"led1\").checked;\n\
    var y = document.getElementById(\"servo1\").value;\n\
    var z = document.getElementById(\"servo2\").value;\n\
    var URL = \"/node/?led1=\"+ x +\"&servo1=\"+ y +\"&servo2=\"+ z;\n\
    ajax.open(\"GET\", URL);\n\
    ajax.send(null);\n\
}\n\
";
htmlCode[5] = "\
</script>\n\
<style>\n\
/* ==== COMMON ==== */\n\
.cmn-toggle {\n\
  position: absolute;\n\
  margin-left: -9999px;\n\
  visibility: hidden;\n\
}\n\
";
htmlCode[6] = "\
.cmn-toggle + label {\n\
  display: block;\n\
  position: relative;\n\
  cursor: pointer;\n\
  outline: none;\n\
  -webkit-user-select: none;\n\
  -moz-user-select: none;\n\
  -ms-user-select: none;\n\
  user-select: none;\n\
}\n\
";
htmlCode[7] = "\
/* ==== SWITCH 1 - ROUND ==== */\n\
input.cmn-toggle-round + label {\n\
  padding: 2px;\n\
  width: 120px;\n\
  height: 60px;\n\
  background-color: #dddddd;\n\
  -webkit-border-radius: 60px;\n\
  -moz-border-radius: 60px;\n\
  -ms-border-radius: 60px;\n\
  -o-border-radius: 60px;\n\
  border-radius: 60px;\n\
}\n\
";
htmlCode[8] = "\
input.cmn-toggle-round + label:before, input.cmn-toggle-round + label:after {\n\
  display: block;\n\
  position: absolute;\n\
  top: 1px;\n\
  left: 1px;\n\
  bottom: 1px;\n\
  content: \"\";\n\
}\n\
";
htmlCode[9] = "\
input.cmn-toggle-round + label:before {\n\
  right: 1px;\n\
  background-color: #f1f1f1;\n\
  -webkit-border-radius: 60px;\n\
  -moz-border-radius: 60px;\n\
  -ms-border-radius: 60px;\n\
  -o-border-radius: 60px;\n\
  border-radius: 60px;\n\
  -webkit-transition: background 0.4s;\n\
  -moz-transition: background 0.4s;\n\
  -o-transition: background 0.4s;\n\
  transition: background 0.4s;\n\
}\n\
";
htmlCode[10] = "\
input.cmn-toggle-round + label:after {\n\
  width: 58px;\n\
  background-color: #fff;\n\
  -webkit-border-radius: 100%;\n\
  -moz-border-radius: 100%;\n\
  -ms-border-radius: 100%;\n\
  -o-border-radius: 100%;\n\
  border-radius: 100%;\n\
  -webkit-box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);\n\
  -moz-box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);\n\
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);\n\
  -webkit-transition: margin 0.4s;\n\
  -moz-transition: margin 0.4s;\n\
  -o-transition: margin 0.4s;\n\
  transition: margin 0.4s;\n\
}\n\
";
htmlCode[11] = "\
input.cmn-toggle-round:checked + label:before {\n\
  background-color: #8ce196;\n\
}\n\
";
htmlCode[12] = "\
input.cmn-toggle-round:checked + label:after {\n\
  margin-left: 60px;\n\
}\n\
";
htmlCode[13] = "\
/* ==== Range ==== */\n\
input[type=range] {\n\
  -webkit-appearance: none;\n\
  margin: 35px 0;\n\
  width: 85%;\n\
}\n\
";
htmlCode[14] = "\
input[type=range]:focus {\n\
  outline: none;\n\
}\n\
input[type=range]::-webkit-slider-runnable-track {\n\
  width: 100%;\n\
  height: 12px;\n\
  cursor: pointer;\n\
  animate: 0.2s;\n\
  box-shadow: 0px 0px 0px #F1F1F1;\n\
  background: #8CE196;\n\
  border-radius: 15px;\n\
  border: 1px solid #DDDDDD;\n\
}\n\
";
htmlCode[15] = "\
input[type=range]::-webkit-slider-thumb {\n\
  box-shadow: 0px 0px 0px #F1F1F1;\n\
  border: 1px solid #DDDDDD;\n\
  height: 50px;\n\
  width: 50px;\n\
  border-radius: 25px;\n\
  background: #FFFFFF;\n\
  cursor: pointer;\n\
  -webkit-appearance: none;\n\
  margin-top: -20px;\n\
}\n\
";
htmlCode[16] = "\
input[type=range]:focus::-webkit-slider-runnable-track {\n\
  background: #8CE196;\n\
}\n\
";
htmlCode[17] = "\
input[type=range]::-moz-range-track {\n\
  width: 100%;\n\
  height: 12px;\n\
  cursor: pointer;\n\
  animate: 0.2s;\n\
  box-shadow: 0px 0px 0px #F1F1F1;\n\
  background: #8CE196;\n\
  border-radius: 15px;\n\
  border: 1px solid #DDDDDD;\n\
}\n\
";
htmlCode[18] = "\
input[type=range]::-moz-range-thumb {\n\
  box-shadow: 0px 0px 0px #F1F1F1;\n\
  border: 1px solid #DDDDDD;\n\
  height: 50px;\n\
  width: 50px;\n\
  border-radius: 25px;\n\
  background: #FFFFFF;\n\
  cursor: pointer;\n\
}\n\
";
htmlCode[19] = "\
input[type=range]::-ms-track {\n\
  width: 100%;\n\
  height: 12px;\n\
  cursor: pointer;\n\
  animate: 0.2s;\n\
  background: transparent;\n\
  border-color: transparent;\n\
  color: transparent;\n\
}\n\
";
htmlCode[20] = "\
input[type=range]::-ms-fill-lower {\n\
  background: #8CE196;\n\
  border: 1px solid #DDDDDD;\n\
  border-radius: 30px;\n\
  box-shadow: 0px 0px 0px #F1F1F1;\n\
}\n\
";
htmlCode[21] = "\
input[type=range]::-ms-fill-upper {\n\
  background: #8CE196;\n\
  border: 1px solid #DDDDDD;\n\
  border-radius: 30px;\n\
  box-shadow: 0px 0px 0px #F1F1F1;\n\
}\n\
";
htmlCode[22] = "\
input[type=range]::-ms-thumb {\n\
  box-shadow: 0px 0px 0px #F1F1F1;\n\
  border: 1px solid #DDDDDD;\n\
  height: 50px;\n\
  width: 50px;\n\
  border-radius: 25px;\n\
  background: #FFFFFF;\n\
  cursor: pointer;\n\
}\n\
";
htmlCode[23] = "\
input[type=range]:focus::-ms-fill-lower {\n\
  background: #8CE196;\n\
}\n\
";
htmlCode[24] = "\
input[type=range]:focus::-ms-fill-upper {\n\
  background: #8CE196;\n\
}\n\
";
htmlCode[25] = "\
</style>\n\
";
htmlCode[26] = "\
</body>\n\
</html>";
}
#endif
